# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: turbomessage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12turbomessage.proto\x12\x07\x63orreos\"S\n\x07Usuario\x12\x14\n\x07usuario\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\ncontrasena\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_usuarioB\r\n\x0b_contrasena\"\xe2\x01\n\x06\x43orreo\x12\x1a\n\ridentificador\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04tema\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x65misor\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x19\n\x0c\x64\x65stinatario\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x16\n\tcontenido\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x12\n\x05leido\x18\x06 \x01(\x08H\x05\x88\x01\x01\x42\x10\n\x0e_identificadorB\x07\n\x05_temaB\t\n\x07_emisorB\x0f\n\r_destinatarioB\x0c\n\n_contenidoB\x08\n\x06_leido\"L\n\x06Status\x12\x14\n\x07success\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x14\n\x07mensaje\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_successB\n\n\x08_mensaje2\xcd\x03\n\x0cTurboMessage\x12\x33\n\x0cnuevoUsuario\x12\x10.correos.Usuario\x1a\x0f.correos.Status\"\x00\x12\x35\n\x0erevisarUsuario\x12\x10.correos.Usuario\x1a\x0f.correos.Status\"\x00\x12\x32\n\x0c\x65nviarCorreo\x12\x0f.correos.Correo\x1a\x0f.correos.Status\"\x00\x12\x37\n\x0e\x63orreosEntrada\x12\x10.correos.Usuario\x1a\x0f.correos.Correo\"\x00\x30\x01\x12\x36\n\rcorreosSalida\x12\x10.correos.Usuario\x1a\x0f.correos.Correo\"\x00\x30\x01\x12<\n\x16\x65liminarCorreosEntrada\x12\x0f.correos.Correo\x1a\x0f.correos.Status\"\x00\x12;\n\x15\x65liminarCorreosSalida\x12\x0f.correos.Correo\x1a\x0f.correos.Status\"\x00\x12\x31\n\x0b\x63orreoLeido\x12\x0f.correos.Correo\x1a\x0f.correos.Status\"\x00\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turbomessage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_USUARIO']._serialized_start=31
  _globals['_USUARIO']._serialized_end=114
  _globals['_CORREO']._serialized_start=117
  _globals['_CORREO']._serialized_end=343
  _globals['_STATUS']._serialized_start=345
  _globals['_STATUS']._serialized_end=421
  _globals['_TURBOMESSAGE']._serialized_start=424
  _globals['_TURBOMESSAGE']._serialized_end=885
# @@protoc_insertion_point(module_scope)
